var annotated_dup =
[
    [ "behaviorOptions", "classbehaviorOptions.html", "classbehaviorOptions" ],
    [ "builtinPacks", "classbuiltinPacks.html", "classbuiltinPacks" ],
    [ "configParser", "classconfigParser.html", "classconfigParser" ],
    [ "connectionOptions", "classconnectionOptions.html", "classconnectionOptions" ],
    [ "customizationOptions", "classcustomizationOptions.html", "classcustomizationOptions" ],
    [ "Downloader", "classDownloader.html", "classDownloader" ],
    [ "fileUtils", "classfileUtils.html", "classfileUtils" ],
    [ "historyParser", "classhistoryParser.html", "classhistoryParser" ],
    [ "inputLabelWidget", "classinputLabelWidget.html", "classinputLabelWidget" ],
    [ "keyboardOptions", "classkeyboardOptions.html", "classkeyboardOptions" ],
    [ "keyboardUtils", "classkeyboardUtils.html", "classkeyboardUtils" ],
    [ "languageList", "classlanguageList.html", "classlanguageList" ],
    [ "languageManager", "classlanguageManager.html", "classlanguageManager" ],
    [ "levelSummary", "classlevelSummary.html", "classlevelSummary" ],
    [ "monitorClient", "classmonitorClient.html", "classmonitorClient" ],
    [ "Net", "classNet.html", "classNet" ],
    [ "OpenTyper", "classOpenTyper.html", "classOpenTyper" ],
    [ "optionsWindow", "classoptionsWindow.html", "classoptionsWindow" ],
    [ "packEditor", "classpackEditor.html", "classpackEditor" ],
    [ "packSelector", "classpackSelector.html", "classpackSelector" ],
    [ "packView", "classpackView.html", "classpackView" ],
    [ "paperConfigDialog", "classpaperConfigDialog.html", "classpaperConfigDialog" ],
    [ "SimpleColorDialog", "classSimpleColorDialog.html", "classSimpleColorDialog" ],
    [ "statsDialog", "classstatsDialog.html", "classstatsDialog" ],
    [ "stringUtils", "classstringUtils.html", "classstringUtils" ],
    [ "studentOptions", "classstudentOptions.html", "classstudentOptions" ],
    [ "timeDialog", "classtimeDialog.html", "classtimeDialog" ],
    [ "Updater", "classUpdater.html", "classUpdater" ],
    [ "UpdaterDialog", "classUpdaterDialog.html", "classUpdaterDialog" ]
];