var annotated_dup =
[
    [ "behaviorOptions", "classbehaviorOptions.html", "classbehaviorOptions" ],
    [ "builtinPacks", "classbuiltinPacks.html", "classbuiltinPacks" ],
    [ "configParser", "classconfigParser.html", "classconfigParser" ],
    [ "customizationOptions", "classcustomizationOptions.html", "classcustomizationOptions" ],
    [ "Downloader", "classDownloader.html", "classDownloader" ],
    [ "fileUtils", "classfileUtils.html", "classfileUtils" ],
    [ "inputLabelWidget", "classinputLabelWidget.html", "classinputLabelWidget" ],
    [ "keyboardOptions", "classkeyboardOptions.html", "classkeyboardOptions" ],
    [ "keyboardUtils", "classkeyboardUtils.html", "classkeyboardUtils" ],
    [ "languageList", "classlanguageList.html", "classlanguageList" ],
    [ "languageManager", "classlanguageManager.html", "classlanguageManager" ],
    [ "levelSummary", "classlevelSummary.html", "classlevelSummary" ],
    [ "Net", "classNet.html", "classNet" ],
    [ "OpenTyper", "classOpenTyper.html", "classOpenTyper" ],
    [ "optionsWindow", "classoptionsWindow.html", "classoptionsWindow" ],
    [ "packEditor", "classpackEditor.html", "classpackEditor" ],
    [ "packSelector", "classpackSelector.html", "classpackSelector" ],
    [ "packView", "classpackView.html", "classpackView" ],
    [ "paperConfigDialog", "classpaperConfigDialog.html", "classpaperConfigDialog" ],
    [ "SimpleColorDialog", "classSimpleColorDialog.html", "classSimpleColorDialog" ],
    [ "stringUtils", "classstringUtils.html", "classstringUtils" ],
    [ "timeDialog", "classtimeDialog.html", "classtimeDialog" ],
    [ "Updater", "classUpdater.html", null ],
    [ "UpdaterDialog", "classUpdaterDialog.html", null ]
];