var annotated_dup =
[
    [ "behaviorOptions", "classbehaviorOptions.html", null ],
    [ "builtinPacks", "classbuiltinPacks.html", null ],
    [ "configParser", "classconfigParser.html", null ],
    [ "customizationOptions", "classcustomizationOptions.html", null ],
    [ "Downloader", "classDownloader.html", null ],
    [ "fileUtils", "classfileUtils.html", "classfileUtils" ],
    [ "inputLabelWidget", "classinputLabelWidget.html", null ],
    [ "keyboardOptions", "classkeyboardOptions.html", null ],
    [ "keyboardUtils", "classkeyboardUtils.html", null ],
    [ "languageList", "classlanguageList.html", null ],
    [ "languageManager", "classlanguageManager.html", null ],
    [ "levelSummary", "classlevelSummary.html", "classlevelSummary" ],
    [ "Net", "classNet.html", null ],
    [ "OpenTyper", "classOpenTyper.html", "classOpenTyper" ],
    [ "optionsWindow", "classoptionsWindow.html", null ],
    [ "packEditor", "classpackEditor.html", null ],
    [ "packSelector", "classpackSelector.html", null ],
    [ "packView", "classpackView.html", null ],
    [ "paperConfigDialog", "classpaperConfigDialog.html", "classpaperConfigDialog" ],
    [ "SimpleColorDialog", "classSimpleColorDialog.html", null ],
    [ "stringUtils", "classstringUtils.html", null ],
    [ "timeDialog", "classtimeDialog.html", null ],
    [ "Updater", "classUpdater.html", null ],
    [ "UpdaterDialog", "classUpdaterDialog.html", null ]
];